// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6gusGFBMtIYWzN_pFNTkU5UGu7vDU_v8',
    appId: '1:414543069387:web:3bbbd1b08740969f0d9b4e',
    messagingSenderId: '414543069387',
    projectId: 'needai-7f3d1',
    authDomain: 'needai-7f3d1.firebaseapp.com',
    storageBucket: 'needai-7f3d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDatA2g17JLiTJxvZd9ZUFImLkI0NIISlI',
    appId: '1:414543069387:android:946a380c6482030b0d9b4e',
    messagingSenderId: '414543069387',
    projectId: 'needai-7f3d1',
    storageBucket: 'needai-7f3d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ZsU30g-BzPqMY7cVr3AyQeBIHhxdNrQ',
    appId: '1:414543069387:ios:6ca00d1f031553730d9b4e',
    messagingSenderId: '414543069387',
    projectId: 'needai-7f3d1',
    storageBucket: 'needai-7f3d1.firebasestorage.app',
<<<<<<< HEAD
    androidClientId: '414543069387-0meiqun7gkqiudu4hiq9713aaeltn55i.apps.googleusercontent.com',
    iosClientId: '414543069387-i8kbjdgagdchrvr3r59n19vr7hpa01ka.apps.googleusercontent.com',
=======
    androidClientId:
        '414543069387-0meiqun7gkqiudu4hiq9713aaeltn55i.apps.googleusercontent.com',
    iosClientId:
        '414543069387-i8kbjdgagdchrvr3r59n19vr7hpa01ka.apps.googleusercontent.com',
>>>>>>> e38632128fb7aef651f6883f5bfb207761ef8b43
    iosBundleId: 'com.example.needai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ZsU30g-BzPqMY7cVr3AyQeBIHhxdNrQ',
    appId: '1:414543069387:ios:6ca00d1f031553730d9b4e',
    messagingSenderId: '414543069387',
    projectId: 'needai-7f3d1',
    storageBucket: 'needai-7f3d1.firebasestorage.app',
    androidClientId: '414543069387-0meiqun7gkqiudu4hiq9713aaeltn55i.apps.googleusercontent.com',
    iosClientId: '414543069387-i8kbjdgagdchrvr3r59n19vr7hpa01ka.apps.googleusercontent.com',
    iosBundleId: 'com.example.needai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6gusGFBMtIYWzN_pFNTkU5UGu7vDU_v8',
    appId: '1:414543069387:web:5c18668ed0b025fb0d9b4e',
    messagingSenderId: '414543069387',
    projectId: 'needai-7f3d1',
    authDomain: 'needai-7f3d1.firebaseapp.com',
    storageBucket: 'needai-7f3d1.firebasestorage.app',
  );

}